import { and, asc, desc, eq, gte, lte, sql } from 'drizzle-orm';
import type { Database } from '../db/client';
import { accountTransfers, accounts, budgetCycles, creditCards, creditCardStatements, cycleCarryovers, expenseCategories, expenses, incomeRules, incomes, notificationSettings, plannedExpenses, recurringExpenses, savingAllocations, savingGoals, savingsRules, userSettings, users } from '../db/schema';
import { AppError } from '../shared/errors';

const now = () => new Date().toISOString();
const newId = (prefix: string) => `${prefix}_${crypto.randomUUID()}`;
const required = <T>(value: T | undefined, resource: string): T => {
  if (!value) throw new AppError('NOT_FOUND', `${resource} was not found`, 404);
  return value;
};

export class AppRepository {
  constructor(private readonly db: Database) {}

  async userBySubject(subject: string) { return this.db.query.users.findFirst({ where: eq(users.auth0UserId, subject) }); }
  async syncUser(subject: string, email: string, displayName: string) {
    const existing = await this.userBySubject(subject); const timestamp = now();
    if (existing) {
      await this.db.update(users).set({ email, displayName, updatedAt: timestamp }).where(eq(users.id, existing.id));
      return { ...existing, email, displayName, updatedAt: timestamp };
    }
    const user = { id: newId('user'), auth0UserId: subject, email, displayName, createdAt: timestamp, updatedAt: timestamp };
    const setting = { id: newId('settings'), userId: user.id, createdAt: timestamp, updatedAt: timestamp };
    await this.db.batch([this.db.insert(users).values(user), this.db.insert(userSettings).values(setting)]);
    return user;
  }
  async settings(userId: string) { return required(await this.db.query.userSettings.findFirst({ where: eq(userSettings.userId, userId) }), 'User settings'); }
  async updateSettings(userId: string, values: Partial<typeof userSettings.$inferInsert>) {
    await this.db.update(userSettings).set({ ...values, updatedAt: now() }).where(eq(userSettings.userId, userId)); return this.settings(userId);
  }

  listAccounts(userId: string, type?: string) { return this.db.select().from(accounts).where(and(eq(accounts.userId, userId), eq(accounts.isActive, true), type ? eq(accounts.type, type) : undefined)).orderBy(accounts.name); }
  async account(userId: string, id: string) { return required(await this.db.query.accounts.findFirst({ where: and(eq(accounts.id, id), eq(accounts.userId, userId)) }), 'Account'); }
  async createAccount(userId: string, input: { name: string; type: string; initialBalance: number }) {
    const timestamp = now(); const value = { id: newId('acc'), userId, ...input, currentBalance: input.initialBalance, isActive: true, createdAt: timestamp, updatedAt: timestamp };
    await this.db.insert(accounts).values(value); return value;
  }
  async updateAccount(userId: string, id: string, values: { name?: string; type?: string }) { await this.account(userId, id); await this.db.update(accounts).set({ ...values, updatedAt: now() }).where(and(eq(accounts.id, id), eq(accounts.userId, userId))); return this.account(userId, id); }
  async deactivateAccount(userId: string, id: string) { await this.account(userId, id); await this.db.update(accounts).set({ isActive: false, updatedAt: now() }).where(and(eq(accounts.id, id), eq(accounts.userId, userId))); }

  listCategories(userId: string) { return this.db.select().from(expenseCategories).where(and(eq(expenseCategories.userId, userId), eq(expenseCategories.isActive, true))).orderBy(expenseCategories.name); }
  async category(userId: string, id: string) { return required(await this.db.query.expenseCategories.findFirst({ where: and(eq(expenseCategories.id, id), eq(expenseCategories.userId, userId)) }), 'Expense category'); }
  async createCategory(userId: string, name: string) { const timestamp = now(); const value = { id: newId('cat'), userId, name, isActive: true, createdAt: timestamp, updatedAt: timestamp }; await this.db.insert(expenseCategories).values(value); return value; }
  async updateCategory(userId: string, id: string, name: string) { await this.category(userId, id); await this.db.update(expenseCategories).set({ name, updatedAt: now() }).where(and(eq(expenseCategories.id, id), eq(expenseCategories.userId, userId))); return this.category(userId, id); }
  async deactivateCategory(userId: string, id: string) { await this.category(userId, id); await this.db.update(expenseCategories).set({ isActive: false, updatedAt: now() }).where(and(eq(expenseCategories.id, id), eq(expenseCategories.userId, userId))); }

  listCards(userId: string) { return this.db.select().from(creditCards).where(and(eq(creditCards.userId, userId), eq(creditCards.isActive, true))).orderBy(creditCards.name); }
  async card(userId: string, id: string) { return required(await this.db.query.creditCards.findFirst({ where: and(eq(creditCards.id, id), eq(creditCards.userId, userId)) }), 'Credit card'); }
  async createCard(userId: string, input: { name: string; closingDay: number; paymentDay: number; withdrawalAccountId: string }) { await this.account(userId, input.withdrawalAccountId); const timestamp = now(); const value = { id: newId('card'), userId, ...input, isActive: true, createdAt: timestamp, updatedAt: timestamp }; await this.db.insert(creditCards).values(value); return value; }
  async updateCard(userId: string, id: string, input: Partial<{ name: string; closingDay: number; paymentDay: number; withdrawalAccountId: string }>) { await this.card(userId, id); if (input.withdrawalAccountId) await this.account(userId, input.withdrawalAccountId); await this.db.update(creditCards).set({ ...input, updatedAt: now() }).where(and(eq(creditCards.id, id), eq(creditCards.userId, userId))); return this.card(userId, id); }
  async deactivateCard(userId: string, id: string) { await this.card(userId, id); await this.db.update(creditCards).set({ isActive: false, updatedAt: now() }).where(and(eq(creditCards.id, id), eq(creditCards.userId, userId))); }

  listTransfers(userId: string, from?: string, to?: string) { return this.db.select().from(accountTransfers).where(and(eq(accountTransfers.userId, userId), from ? gte(accountTransfers.transferDate, from) : undefined, to ? lte(accountTransfers.transferDate, to) : undefined)).orderBy(desc(accountTransfers.transferDate)); }
  async createTransfer(userId: string, input: { fromAccountId: string; toAccountId: string; amount: number; transferDate: string; memo?: string }) {
    const [fromAccount] = await Promise.all([this.account(userId, input.fromAccountId), this.account(userId, input.toAccountId)]);
    if (fromAccount.currentBalance < input.amount) throw new AppError('CONFLICT', 'The source account has insufficient funds', 409);
    const timestamp = now(); const value = { id: newId('transfer'), userId, ...input, memo: input.memo ?? null, createdAt: timestamp, updatedAt: timestamp };
    await this.db.batch([this.db.insert(accountTransfers).values(value), this.db.update(accounts).set({ currentBalance: sql`${accounts.currentBalance} - ${input.amount}`, updatedAt: timestamp }).where(and(eq(accounts.id, input.fromAccountId), eq(accounts.userId, userId))), this.db.update(accounts).set({ currentBalance: sql`${accounts.currentBalance} + ${input.amount}`, updatedAt: timestamp }).where(and(eq(accounts.id, input.toAccountId), eq(accounts.userId, userId)))]);
    return value;
  }

  listCycles(userId: string, from?: string, to?: string) { return this.db.select().from(budgetCycles).where(and(eq(budgetCycles.userId, userId), from ? gte(budgetCycles.endDate, from) : undefined, to ? lte(budgetCycles.startDate, to) : undefined)).orderBy(desc(budgetCycles.startDate)); }
  async cycle(userId: string, id: string) { return required(await this.db.query.budgetCycles.findFirst({ where: and(eq(budgetCycles.id, id), eq(budgetCycles.userId, userId)) }), 'Budget cycle'); }
  async currentCycle(userId: string, date: string) { return required(await this.db.query.budgetCycles.findFirst({ where: and(eq(budgetCycles.userId, userId), lte(budgetCycles.startDate, date), gte(budgetCycles.endDate, date)) }), 'Current budget cycle'); }
  async overlappingCycle(userId: string, startDate: string, endDate: string, exceptId?: string) { return this.db.query.budgetCycles.findFirst({ where: and(eq(budgetCycles.userId, userId), lte(budgetCycles.startDate, endDate), gte(budgetCycles.endDate, startDate), exceptId ? sql`${budgetCycles.id} <> ${exceptId}` : undefined) }); }
  async createCycle(userId: string, input: { name: string; startDate: string; endDate: string; resetType: string }) { const timestamp = now(); const value = { id: newId('cycle'), userId, ...input, isClosed: false, createdAt: timestamp, updatedAt: timestamp }; await this.db.insert(budgetCycles).values(value); return value; }
  async updateCycle(userId: string, id: string, input: Partial<{ name: string; startDate: string; endDate: string; resetType: string }>) { await this.cycle(userId, id); await this.db.update(budgetCycles).set({ ...input, updatedAt: now() }).where(and(eq(budgetCycles.id, id), eq(budgetCycles.userId, userId))); return this.cycle(userId, id); }
  async nextCycle(userId: string, afterDate: string) { return this.db.query.budgetCycles.findFirst({ where: and(eq(budgetCycles.userId, userId), sql`${budgetCycles.startDate} > ${afterDate}`), orderBy: asc(budgetCycles.startDate) }); }
  async deleteCycle(userId: string, id: string) { await this.cycle(userId, id); const [income] = await this.db.select({ count: sql<number>`count(*)` }).from(incomes).where(and(eq(incomes.userId, userId), eq(incomes.cycleId, id))); const [expense] = await this.db.select({ count: sql<number>`count(*)` }).from(expenses).where(and(eq(expenses.userId, userId), eq(expenses.cycleId, id))); if ((income?.count ?? 0) > 0 || (expense?.count ?? 0) > 0) throw new AppError('CONFLICT', 'A cycle containing income or expenses cannot be deleted', 409); await this.db.delete(budgetCycles).where(and(eq(budgetCycles.id, id), eq(budgetCycles.userId, userId))); }
  async closeCycle(userId: string, id: string, amount: number, policy: string, toCycleId?: string) { await this.cycle(userId, id); const timestamp = now(); const carryover = { id: newId('carry'), userId, fromCycleId: id, toCycleId: toCycleId ?? null, amount, policy, createdAt: timestamp, updatedAt: timestamp }; await this.db.batch([this.db.insert(cycleCarryovers).values(carryover), this.db.update(budgetCycles).set({ isClosed: true, updatedAt: timestamp }).where(and(eq(budgetCycles.id, id), eq(budgetCycles.userId, userId)))]); return carryover; }

  listIncomes(userId: string, filters: { cycleId?: string; from?: string; to?: string; type?: string }) { return this.db.select().from(incomes).where(and(eq(incomes.userId, userId), filters.cycleId ? eq(incomes.cycleId, filters.cycleId) : undefined, filters.from ? gte(incomes.incomeDate, filters.from) : undefined, filters.to ? lte(incomes.incomeDate, filters.to) : undefined, filters.type ? eq(incomes.type, filters.type) : undefined)).orderBy(desc(incomes.incomeDate)); }
  async income(userId: string, id: string) { return required(await this.db.query.incomes.findFirst({ where: and(eq(incomes.id, id), eq(incomes.userId, userId)) }), 'Income'); }
  async createIncome(userId: string, input: { cycleId: string; accountId: string; name: string; amount: number; incomeDate: string; type: string }) { await Promise.all([this.cycle(userId, input.cycleId), this.account(userId, input.accountId)]); const timestamp = now(); const value = { id: newId('inc'), userId, ...input, createdAt: timestamp, updatedAt: timestamp }; await this.db.batch([this.db.insert(incomes).values(value), this.db.update(accounts).set({ currentBalance: sql`${accounts.currentBalance} + ${input.amount}`, updatedAt: timestamp }).where(and(eq(accounts.id, input.accountId), eq(accounts.userId, userId)))]); return value; }
  async updateIncome(userId: string, id: string, input: Partial<{ cycleId: string; accountId: string; name: string; amount: number; incomeDate: string; type: string }>) { const old = await this.income(userId, id); if (input.cycleId) await this.cycle(userId, input.cycleId); if (input.accountId) await this.account(userId, input.accountId); const targetAccount = input.accountId ?? old.accountId; const targetAmount = input.amount ?? old.amount; const timestamp = now(); const statements = [this.db.update(incomes).set({ ...input, updatedAt: timestamp }).where(and(eq(incomes.id, id), eq(incomes.userId, userId))), this.db.update(accounts).set({ currentBalance: sql`${accounts.currentBalance} - ${old.amount}`, updatedAt: timestamp }).where(and(eq(accounts.id, old.accountId), eq(accounts.userId, userId))), this.db.update(accounts).set({ currentBalance: sql`${accounts.currentBalance} + ${targetAmount}`, updatedAt: timestamp }).where(and(eq(accounts.id, targetAccount), eq(accounts.userId, userId)))]; await this.db.batch(statements as [typeof statements[0], typeof statements[1], typeof statements[2]]); return this.income(userId, id); }
  async deleteIncome(userId: string, id: string) { const old = await this.income(userId, id); await this.db.batch([this.db.delete(incomes).where(and(eq(incomes.id, id), eq(incomes.userId, userId))), this.db.update(accounts).set({ currentBalance: sql`${accounts.currentBalance} - ${old.amount}`, updatedAt: now() }).where(and(eq(accounts.id, old.accountId), eq(accounts.userId, userId)))]); }

  listExpenses(userId: string, filters: { cycleId?: string; from?: string; to?: string; categoryId?: string; paymentMethod?: string }, limit?: number) { return this.db.select().from(expenses).where(and(eq(expenses.userId, userId), filters.cycleId ? eq(expenses.cycleId, filters.cycleId) : undefined, filters.from ? gte(expenses.expenseDate, filters.from) : undefined, filters.to ? lte(expenses.expenseDate, filters.to) : undefined, filters.categoryId ? eq(expenses.categoryId, filters.categoryId) : undefined, filters.paymentMethod ? eq(expenses.paymentMethod, filters.paymentMethod) : undefined)).orderBy(desc(expenses.expenseDate), desc(expenses.createdAt)).limit(limit ?? 500); }
  async expense(userId: string, id: string) { return required(await this.db.query.expenses.findFirst({ where: and(eq(expenses.id, id), eq(expenses.userId, userId)) }), 'Expense'); }
  async validateExpenseRefs(userId: string, input: { cycleId: string; accountId?: string | null; creditCardId?: string | null; categoryId: string }) { await Promise.all([this.cycle(userId, input.cycleId), this.category(userId, input.categoryId), input.accountId ? this.account(userId, input.accountId) : undefined, input.creditCardId ? this.card(userId, input.creditCardId) : undefined]); }
  async createExpense(userId: string, input: { cycleId: string; accountId?: string | null; creditCardId?: string | null; categoryId: string; name: string; amount: number; expenseDate: string; paymentMethod: string; memo?: string | null }) { await this.validateExpenseRefs(userId, input); const timestamp = now(); const value = { id: newId('exp'), userId, ...input, accountId: input.accountId ?? null, creditCardId: input.creditCardId ?? null, memo: input.memo ?? null, isAdjustment: false, createdAt: timestamp, updatedAt: timestamp }; const insert = this.db.insert(expenses).values(value); if (value.accountId && value.paymentMethod !== 'credit_card') await this.db.batch([insert, this.db.update(accounts).set({ currentBalance: sql`${accounts.currentBalance} - ${value.amount}`, updatedAt: timestamp }).where(and(eq(accounts.id, value.accountId), eq(accounts.userId, userId)))]); else await insert; return value; }
  async updateExpense(userId: string, id: string, input: Partial<{ cycleId: string; accountId: string | null; creditCardId: string | null; categoryId: string; name: string; amount: number; expenseDate: string; paymentMethod: string; memo: string | null }>) {
    const old = await this.expense(userId, id); const merged = { ...old, ...input }; await this.validateExpenseRefs(userId, merged); const timestamp = now();
    const update = this.db.update(expenses).set({ ...input, updatedAt: timestamp }).where(and(eq(expenses.id, id), eq(expenses.userId, userId)));
    const restore = old.accountId && old.paymentMethod !== 'credit_card' ? this.db.update(accounts).set({ currentBalance: sql`${accounts.currentBalance} + ${old.amount}`, updatedAt: timestamp }).where(and(eq(accounts.id, old.accountId), eq(accounts.userId, userId))) : undefined;
    const deduct = merged.accountId && merged.paymentMethod !== 'credit_card' ? this.db.update(accounts).set({ currentBalance: sql`${accounts.currentBalance} - ${merged.amount}`, updatedAt: timestamp }).where(and(eq(accounts.id, merged.accountId), eq(accounts.userId, userId))) : undefined;
    if (restore && deduct) await this.db.batch([update, restore, deduct]);
    else if (restore) await this.db.batch([update, restore]);
    else if (deduct) await this.db.batch([update, deduct]);
    else await update;
    return this.expense(userId, id);
  }
  async deleteExpense(userId: string, id: string) { const old = await this.expense(userId, id); const deletion = this.db.delete(expenses).where(and(eq(expenses.id, id), eq(expenses.userId, userId))); if (old.accountId && old.paymentMethod !== 'credit_card') await this.db.batch([deletion, this.db.update(accounts).set({ currentBalance: sql`${accounts.currentBalance} + ${old.amount}`, updatedAt: now() }).where(and(eq(accounts.id, old.accountId), eq(accounts.userId, userId)))]); else await deletion; }

  listPlanned(userId: string, cycleId?: string, status?: string) { return this.db.select().from(plannedExpenses).where(and(eq(plannedExpenses.userId, userId), cycleId ? eq(plannedExpenses.cycleId, cycleId) : undefined, status ? eq(plannedExpenses.status, status) : undefined)).orderBy(plannedExpenses.plannedDate); }
  async planned(userId: string, id: string) { return required(await this.db.query.plannedExpenses.findFirst({ where: and(eq(plannedExpenses.id, id), eq(plannedExpenses.userId, userId)) }), 'Planned expense'); }
  async createPlanned(userId: string, input: { cycleId: string; accountId?: string | null; creditCardId?: string | null; categoryId: string; name: string; estimatedAmount: number; plannedDate: string; paymentMethod: string; reflectToBudget: boolean; memo?: string }) { await this.validateExpenseRefs(userId, input); const timestamp = now(); const value = { id: newId('pexp'), userId, ...input, accountId: input.accountId ?? null, creditCardId: input.creditCardId ?? null, actualAmount: null, confirmedDate: null, status: 'planned', memo: input.memo ?? null, createdAt: timestamp, updatedAt: timestamp }; await this.db.insert(plannedExpenses).values(value); return value; }
  async confirmPlanned(userId: string, id: string, actualAmount: number, confirmedDate: string) { const planned = await this.planned(userId, id); if (planned.status !== 'planned') throw new AppError('CONFLICT', 'The planned expense is already resolved', 409); const timestamp = now(); const expense = { id: newId('exp'), userId, cycleId: planned.cycleId, accountId: planned.accountId, creditCardId: planned.creditCardId, categoryId: planned.categoryId, recurringExpenseId: null, plannedExpenseId: planned.id, name: planned.name, amount: actualAmount, expenseDate: confirmedDate, paymentMethod: planned.paymentMethod, memo: planned.memo, isAdjustment: false, createdAt: timestamp, updatedAt: timestamp }; const update = this.db.update(plannedExpenses).set({ actualAmount, confirmedDate, status: 'confirmed', updatedAt: timestamp }).where(and(eq(plannedExpenses.id, id), eq(plannedExpenses.userId, userId))); if (planned.accountId && planned.paymentMethod !== 'credit_card') await this.db.batch([this.db.insert(expenses).values(expense), update, this.db.update(accounts).set({ currentBalance: sql`${accounts.currentBalance} - ${actualAmount}`, updatedAt: timestamp }).where(and(eq(accounts.id, planned.accountId), eq(accounts.userId, userId)))]); else await this.db.batch([this.db.insert(expenses).values(expense), update]); return { plannedExpenseId: id, expenseId: expense.id, status: 'confirmed', actualAmount }; }

  listRecurring(userId: string) { return this.db.select().from(recurringExpenses).where(and(eq(recurringExpenses.userId, userId), eq(recurringExpenses.isActive, true))).orderBy(recurringExpenses.billingDay); }
  async recurring(userId: string, id: string) { return required(await this.db.query.recurringExpenses.findFirst({ where: and(eq(recurringExpenses.id, id), eq(recurringExpenses.userId, userId)) }), 'Recurring expense'); }
  async validatePaymentRefs(userId: string, input: { accountId?: string | null; creditCardId?: string | null; categoryId: string }) { await Promise.all([this.category(userId, input.categoryId), input.accountId ? this.account(userId, input.accountId) : undefined, input.creditCardId ? this.card(userId, input.creditCardId) : undefined]); }
  async createRecurring(userId: string, input: { accountId?: string | null; creditCardId?: string | null; categoryId: string; name: string; amount?: number; paymentMethod: string; billingDay: number; isAmountFixed: boolean; estimatedAmount?: number }) { await this.validatePaymentRefs(userId, input); const timestamp = now(); const value = { id: newId('rec'), userId, ...input, accountId: input.accountId ?? null, creditCardId: input.creditCardId ?? null, amount: input.amount ?? null, estimatedAmount: input.estimatedAmount ?? null, isActive: true, createdAt: timestamp, updatedAt: timestamp }; await this.db.insert(recurringExpenses).values(value); return value; }
  async updateRecurring(userId: string, id: string, input: Partial<{ accountId: string | null; creditCardId: string | null; categoryId: string; name: string; amount: number | null; paymentMethod: string; billingDay: number; isAmountFixed: boolean; estimatedAmount: number | null }>) { const old = await this.recurring(userId, id); const merged = { ...old, ...input }; await this.validatePaymentRefs(userId, merged); await this.db.update(recurringExpenses).set({ ...input, updatedAt: now() }).where(and(eq(recurringExpenses.id, id), eq(recurringExpenses.userId, userId))); return this.recurring(userId, id); }
  async deactivateRecurring(userId: string, id: string) { await this.recurring(userId, id); await this.db.update(recurringExpenses).set({ isActive: false, updatedAt: now() }).where(and(eq(recurringExpenses.id, id), eq(recurringExpenses.userId, userId))); }
  async generateRecurring(userId: string, id: string, cycleId: string, targetDate: string) { const [recurring, cycle] = await Promise.all([this.recurring(userId, id), this.cycle(userId, cycleId)]); if (targetDate < cycle.startDate || targetDate > cycle.endDate) throw new AppError('VALIDATION_ERROR', 'targetDate must be inside the cycle', 400); const timestamp = now(); if (!recurring.isAmountFixed) { const planned = { id: newId('pexp'), userId, cycleId, accountId: recurring.accountId, creditCardId: recurring.creditCardId, categoryId: recurring.categoryId, name: recurring.name, estimatedAmount: recurring.estimatedAmount ?? 0, actualAmount: null, plannedDate: targetDate, confirmedDate: null, paymentMethod: recurring.paymentMethod, reflectToBudget: true, status: 'planned', memo: null, createdAt: timestamp, updatedAt: timestamp }; await this.db.insert(plannedExpenses).values(planned); return planned; } const amount = recurring.amount ?? 0; const expense = { id: newId('exp'), userId, cycleId, accountId: recurring.accountId, creditCardId: recurring.creditCardId, categoryId: recurring.categoryId, recurringExpenseId: recurring.id, plannedExpenseId: null, name: recurring.name, amount, expenseDate: targetDate, paymentMethod: recurring.paymentMethod, memo: null, isAdjustment: false, createdAt: timestamp, updatedAt: timestamp }; const insert = this.db.insert(expenses).values(expense); if (recurring.accountId && recurring.paymentMethod !== 'credit_card') await this.db.batch([insert, this.db.update(accounts).set({ currentBalance: sql`${accounts.currentBalance} - ${amount}`, updatedAt: timestamp }).where(and(eq(accounts.id, recurring.accountId), eq(accounts.userId, userId)))]); else await insert; return expense; }

  listIncomeRules(userId: string) { return this.db.select().from(incomeRules).where(and(eq(incomeRules.userId, userId), eq(incomeRules.isActive, true))).orderBy(incomeRules.incomeDay); }
  async incomeRule(userId: string, id: string) { return required(await this.db.query.incomeRules.findFirst({ where: and(eq(incomeRules.id, id), eq(incomeRules.userId, userId)) }), 'Income rule'); }
  async createIncomeRule(userId: string, input: { accountId: string; name: string; amount: number; incomeDay: number; inputMode: string }) { await this.account(userId, input.accountId); const timestamp = now(); const value = { id: newId('irule'), userId, ...input, isActive: true, createdAt: timestamp, updatedAt: timestamp }; await this.db.insert(incomeRules).values(value); return value; }
  async generateIncomeRule(userId: string, id: string, cycleId: string, incomeDate: string, amount?: number) { const rule = await this.incomeRule(userId, id); return this.createIncome(userId, { cycleId, accountId: rule.accountId, name: rule.name, amount: amount ?? rule.amount, incomeDate, type: 'salary' }); }

  listSavingGoals(userId: string) { return this.db.select().from(savingGoals).where(and(eq(savingGoals.userId, userId), eq(savingGoals.isActive, true))).orderBy(savingGoals.name); }
  async savingGoal(userId: string, id: string) { return required(await this.db.query.savingGoals.findFirst({ where: and(eq(savingGoals.id, id), eq(savingGoals.userId, userId)) }), 'Saving goal'); }
  async createSavingGoal(userId: string, input: { name: string; targetAmount: number }) { const timestamp = now(); const value = { id: newId('goal'), userId, ...input, currentAmount: 0, isActive: true, createdAt: timestamp, updatedAt: timestamp }; await this.db.insert(savingGoals).values(value); return value; }
  async updateSavingGoal(userId: string, id: string, input: Partial<{ name: string; targetAmount: number }>) { await this.savingGoal(userId, id); await this.db.update(savingGoals).set({ ...input, updatedAt: now() }).where(and(eq(savingGoals.id, id), eq(savingGoals.userId, userId))); return this.savingGoal(userId, id); }
  async deactivateSavingGoal(userId: string, id: string) { await this.savingGoal(userId, id); await this.db.update(savingGoals).set({ isActive: false, updatedAt: now() }).where(and(eq(savingGoals.id, id), eq(savingGoals.userId, userId))); }
  listSavingsRules(userId: string) { return this.db.select().from(savingsRules).where(and(eq(savingsRules.userId, userId), eq(savingsRules.isActive, true))).orderBy(savingsRules.name); }
  async createSavingsRule(userId: string, input: { name: string; type: string; amount?: number; percentage?: number }) { const timestamp = now(); const value = { id: newId('srule'), userId, ...input, amount: input.amount ?? null, percentage: input.percentage ?? null, isActive: true, createdAt: timestamp, updatedAt: timestamp }; await this.db.insert(savingsRules).values(value); return value; }
  async createSavingAllocation(userId: string, input: { cycleId: string; incomeId?: string; savingGoalId: string; amount: number }) { await Promise.all([this.cycle(userId, input.cycleId), this.savingGoal(userId, input.savingGoalId), input.incomeId ? this.income(userId, input.incomeId) : undefined]); const timestamp = now(); const value = { id: newId('allocation'), userId, ...input, incomeId: input.incomeId ?? null, createdAt: timestamp, updatedAt: timestamp }; await this.db.batch([this.db.insert(savingAllocations).values(value), this.db.update(savingGoals).set({ currentAmount: sql`${savingGoals.currentAmount} + ${input.amount}`, updatedAt: timestamp }).where(and(eq(savingGoals.id, input.savingGoalId), eq(savingGoals.userId, userId)))]); return value; }

  listNotifications(userId: string) { return this.db.select().from(notificationSettings).where(eq(notificationSettings.userId, userId)).orderBy(notificationSettings.type); }
  async updateNotification(userId: string, type: string, input: { enabled: boolean; timing?: string | null }) { const timestamp = now(); await this.db.insert(notificationSettings).values({ id: newId('notification'), userId, type, enabled: input.enabled, timing: input.timing ?? null, createdAt: timestamp, updatedAt: timestamp }).onConflictDoUpdate({ target: [notificationSettings.userId, notificationSettings.type], set: { enabled: input.enabled, timing: input.timing ?? null, updatedAt: timestamp } }); return required(await this.db.query.notificationSettings.findFirst({ where: and(eq(notificationSettings.userId, userId), eq(notificationSettings.type, type)) }), 'Notification setting'); }

  async budgetTotals(userId: string, cycleId: string) {
    const [income] = await this.db.select({ total: sql<number>`coalesce(sum(${incomes.amount}), 0)` }).from(incomes).where(and(eq(incomes.userId, userId), eq(incomes.cycleId, cycleId)));
    const [actual] = await this.db.select({ total: sql<number>`coalesce(sum(${expenses.amount}), 0)`, card: sql<number>`coalesce(sum(case when ${expenses.paymentMethod} = 'credit_card' then ${expenses.amount} else 0 end), 0)` }).from(expenses).where(and(eq(expenses.userId, userId), eq(expenses.cycleId, cycleId), sql`${expenses.recurringExpenseId} is null`, sql`${expenses.plannedExpenseId} is null`));
    const [planned] = await this.db.select({ total: sql<number>`coalesce(sum(case when ${plannedExpenses.actualAmount} is not null then ${plannedExpenses.actualAmount} else ${plannedExpenses.estimatedAmount} end), 0)` }).from(plannedExpenses).where(and(eq(plannedExpenses.userId, userId), eq(plannedExpenses.cycleId, cycleId), eq(plannedExpenses.reflectToBudget, true), sql`${plannedExpenses.status} <> 'cancelled'`));
    const [fixed] = await this.db.select({ total: sql<number>`coalesce(sum(coalesce(${recurringExpenses.amount}, ${recurringExpenses.estimatedAmount}, 0)), 0)` }).from(recurringExpenses).where(and(eq(recurringExpenses.userId, userId), eq(recurringExpenses.isActive, true)));
    const [savings] = await this.db.select({ total: sql<number>`coalesce(sum(${savingAllocations.amount}), 0)` }).from(savingAllocations).where(and(eq(savingAllocations.userId, userId), eq(savingAllocations.cycleId, cycleId)));
    const [carry] = await this.db.select({ total: sql<number>`coalesce(sum(${cycleCarryovers.amount}), 0)` }).from(cycleCarryovers).where(and(eq(cycleCarryovers.userId, userId), eq(cycleCarryovers.toCycleId, cycleId), eq(cycleCarryovers.policy, 'add_to_next_cycle')));
    return { income: income?.total ?? 0, actual: actual?.total ?? 0, card: actual?.card ?? 0, planned: planned?.total ?? 0, fixed: fixed?.total ?? 0, savings: savings?.total ?? 0, carryover: carry?.total ?? 0 };
  }

  listStatements(userId: string, creditCardId?: string, cycleId?: string) { return this.db.select().from(creditCardStatements).where(and(eq(creditCardStatements.userId, userId), creditCardId ? eq(creditCardStatements.creditCardId, creditCardId) : undefined, cycleId ? eq(creditCardStatements.cycleId, cycleId) : undefined)).orderBy(desc(creditCardStatements.paymentDate)); }
  async statement(userId: string, id: string) { return required(await this.db.query.creditCardStatements.findFirst({ where: and(eq(creditCardStatements.id, id), eq(creditCardStatements.userId, userId)) }), 'Credit card statement'); }
  async statementExpenses(userId: string, creditCardId: string, from: string, to: string) { return this.db.select().from(expenses).where(and(eq(expenses.userId, userId), eq(expenses.creditCardId, creditCardId), gte(expenses.expenseDate, from), lte(expenses.expenseDate, to))).orderBy(expenses.expenseDate); }
  async createStatement(userId: string, input: { creditCardId: string; cycleId: string; statementStartDate: string; statementEndDate: string; paymentDate: string; billedAmount: number }) { await Promise.all([this.card(userId, input.creditCardId), this.cycle(userId, input.cycleId)]); const matched = await this.statementExpenses(userId, input.creditCardId, input.statementStartDate, input.statementEndDate); const recordedAmount = matched.reduce((sum, item) => sum + item.amount, 0); const differenceAmount = input.billedAmount - recordedAmount; const timestamp = now(); const value = { id: newId('stmt'), userId, ...input, recordedAmount, differenceAmount, status: differenceAmount === 0 ? 'matched' : 'unmatched', paidAt: null, createdAt: timestamp, updatedAt: timestamp }; await this.db.insert(creditCardStatements).values(value); return value; }
  async ignoreStatementDifference(userId: string, id: string) { await this.statement(userId, id); await this.db.update(creditCardStatements).set({ status: 'ignored', updatedAt: now() }).where(and(eq(creditCardStatements.id, id), eq(creditCardStatements.userId, userId))); return this.statement(userId, id); }
  async addStatementAdjustment(userId: string, statementId: string, categoryId: string, amount: number, name: string, memo?: string) { const statement = await this.statement(userId, statementId); await this.category(userId, categoryId); const timestamp = now(); const expense = { id: newId('exp'), userId, cycleId: statement.cycleId, accountId: null, creditCardId: statement.creditCardId, categoryId, recurringExpenseId: null, plannedExpenseId: null, name, amount, expenseDate: statement.statementEndDate, paymentMethod: 'credit_card', memo: memo ?? null, isAdjustment: true, createdAt: timestamp, updatedAt: timestamp }; const recordedAmount = statement.recordedAmount + amount; const differenceAmount = statement.billedAmount - recordedAmount; await this.db.batch([this.db.insert(expenses).values(expense), this.db.update(creditCardStatements).set({ recordedAmount, differenceAmount, status: differenceAmount === 0 ? 'adjusted' : 'unmatched', updatedAt: timestamp }).where(and(eq(creditCardStatements.id, statementId), eq(creditCardStatements.userId, userId)))]); return this.statement(userId, statementId); }
  async markStatementPaid(userId: string, id: string) { const statement = await this.statement(userId, id); if (statement.status === 'paid') throw new AppError('CONFLICT', 'The statement is already paid', 409); if (!['matched', 'adjusted', 'ignored'].includes(statement.status)) throw new AppError('CONFLICT', 'Reconcile or explicitly ignore the statement difference before payment', 409); const card = await this.card(userId, statement.creditCardId); const account = await this.account(userId, card.withdrawalAccountId); if (account.currentBalance < statement.billedAmount) throw new AppError('CONFLICT', 'The withdrawal account has insufficient funds', 409); const timestamp = now(); await this.db.batch([this.db.update(accounts).set({ currentBalance: sql`${accounts.currentBalance} - ${statement.billedAmount}`, updatedAt: timestamp }).where(and(eq(accounts.id, card.withdrawalAccountId), eq(accounts.userId, userId))), this.db.update(creditCardStatements).set({ status: 'paid', paidAt: timestamp, updatedAt: timestamp }).where(and(eq(creditCardStatements.id, id), eq(creditCardStatements.userId, userId)))]); return { ...(await this.statement(userId, id)), withdrawalAccountId: card.withdrawalAccountId, paidAmount: statement.billedAmount };
  }
}
