import { Children, cloneElement, createContext, forwardRef, isValidElement, useContext, useState, type AnchorHTMLAttributes, type ButtonHTMLAttributes, type HTMLAttributes, type InputHTMLAttributes, type ReactElement, type ReactNode, type SelectHTMLAttributes, type TextareaHTMLAttributes } from 'react';
import { Dialog, DropdownMenu as RadixDropdown, Switch as RadixSwitch, Tooltip as RadixTooltip } from 'radix-ui';
import { LoaderCircle, X } from 'lucide-react';
import { cn } from '../../lib/cn';

export const UIProvider = ({ children }: { children: ReactNode }) => <>{children}</>;

type ButtonProps = ButtonHTMLAttributes<HTMLButtonElement> & {
  onPress?: () => void; isLoading?: boolean; isDisabled?: boolean; isIconOnly?: boolean;
  startContent?: ReactNode; endContent?: ReactNode; variant?: 'light' | 'bordered' | 'flat' | 'solid';
  color?: 'primary' | 'danger' | 'success' | 'warning'; size?: 'sm' | 'md' | 'lg'; radius?: string;
};
export const Button = forwardRef<HTMLButtonElement, ButtonProps>(function Button({ className, children, onPress, onClick, isLoading, isDisabled, disabled, isIconOnly, startContent, endContent, variant = 'solid', color, size = 'md', type = 'button', ...props }, ref) {
  const base = 'inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-xl font-medium outline-none transition-all duration-200 focus-visible:ring-2 focus-visible:ring-blue-500/35 disabled:pointer-events-none disabled:opacity-45 active:scale-[.98]';
  const variants = variant === 'bordered' ? 'border border-input bg-card text-foreground shadow-[0_1px_2px_rgba(0,0,0,.03)] hover:bg-secondary' : variant === 'light' ? 'bg-transparent text-muted-foreground hover:bg-secondary hover:text-foreground' : variant === 'flat' ? 'bg-secondary text-secondary-foreground hover:brightness-95' : color === 'danger' ? 'bg-red-700 text-white shadow-sm hover:bg-red-800' : color === 'success' ? 'bg-emerald-700 text-white shadow-sm hover:bg-emerald-800' : 'bg-zinc-950 text-white shadow-[0_1px_2px_rgba(0,0,0,.15)] hover:bg-zinc-800 dark:bg-zinc-100 dark:text-zinc-950 dark:hover:bg-white';
  const sizes = size === 'sm' ? 'h-8 px-3 text-xs' : size === 'lg' ? 'h-11 px-5 text-sm' : 'h-10 px-4 text-sm';
  return <button ref={ref} type={type} className={cn(base, variants, sizes, isIconOnly && 'w-10 px-0', className)} disabled={disabled || isDisabled || isLoading} onClick={(event) => { onClick?.(event); if (!event.defaultPrevented) onPress?.(); }} {...props}>{isLoading ? <LoaderCircle className="h-4 w-4 animate-spin" /> : startContent}{children}{!isLoading && endContent}</button>;
});

export const Card = ({ className, ...props }: HTMLAttributes<HTMLDivElement>) => <div className={cn('rounded-[22px] border border-border bg-card text-card-foreground shadow-[0_1px_2px_rgba(0,0,0,.035),0_12px_32px_rgba(0,0,0,.045)] backdrop-blur-xl', className)} {...props} />;
export const CardBody = ({ className, ...props }: HTMLAttributes<HTMLDivElement>) => <div className={cn('p-5', className)} {...props} />;

type InputProps = Omit<InputHTMLAttributes<HTMLInputElement>, 'size'> & { onValueChange?: (value: string) => void; startContent?: ReactNode; endContent?: ReactNode; isRequired?: boolean; classNames?: Record<string, string> };
export const Input = forwardRef<HTMLInputElement, InputProps>(function Input({ className, onChange, onValueChange, startContent, endContent, isRequired, required, classNames: _classNames, ...props }, ref) {
  return <div className={cn('flex h-11 w-full items-center gap-2 rounded-xl border border-input bg-card px-3 shadow-[inset_0_1px_0_rgba(255,255,255,.12),0_1px_2px_rgba(0,0,0,.03)] transition focus-within:border-link focus-within:ring-4 focus-within:ring-link/20', className)}>{startContent}<input ref={ref} className="min-w-0 flex-1 bg-transparent text-sm text-foreground outline-none placeholder:text-muted-foreground" required={required || isRequired} onChange={(e) => { onChange?.(e); onValueChange?.(e.target.value); }} {...props} />{endContent}</div>;
});
export const Textarea = forwardRef<HTMLTextAreaElement, TextareaHTMLAttributes<HTMLTextAreaElement> & { onValueChange?: (value: string) => void }>(function Textarea({ className, onChange, onValueChange, ...props }, ref) { return <textarea ref={ref} className={cn('min-h-24 w-full resize-y rounded-xl border border-input bg-card px-3 py-2.5 text-sm text-foreground outline-none shadow-[0_1px_2px_rgba(0,0,0,.03)] transition placeholder:text-muted-foreground focus:border-link focus:ring-4 focus:ring-link/20', className)} onChange={(e) => { onChange?.(e); onValueChange?.(e.target.value); }} {...props} />; });

type SelectProps = SelectHTMLAttributes<HTMLSelectElement> & { selectedKeys?: Iterable<string>; defaultSelectedKeys?: Iterable<string>; isRequired?: boolean; placeholder?: string; classNames?: Record<string, string> };
export function Select({ className, selectedKeys, defaultSelectedKeys, isRequired, required, placeholder, children, ...props }: SelectProps) {
  const selected = selectedKeys ? Array.from(selectedKeys)[0] : undefined; const initial = defaultSelectedKeys ? Array.from(defaultSelectedKeys)[0] : undefined;
  const options = Children.map(children, (child) => isValidElement(child) ? cloneElement(child as ReactElement<React.OptionHTMLAttributes<HTMLOptionElement>>, { value: child.key ?? undefined }) : child);
  return <select className={cn('h-11 w-full appearance-none rounded-xl border border-input bg-card px-3 text-sm text-foreground outline-none shadow-[0_1px_2px_rgba(0,0,0,.03)] transition focus:border-link focus:ring-4 focus:ring-link/20', className)} value={selected} defaultValue={selected === undefined ? initial : undefined} required={required || isRequired} {...props}>{placeholder && <option value="">{placeholder}</option>}{options}</select>;
}
export const SelectItem = ({ children, ...props }: { children: ReactNode; key?: string } & React.OptionHTMLAttributes<HTMLOptionElement>) => <option {...props}>{children}</option>;

type SwitchProps = { isSelected?: boolean; defaultSelected?: boolean; onValueChange?: (value: boolean) => void; isDisabled?: boolean; name?: string; 'aria-label'?: string };
export function Switch({ isSelected, defaultSelected = false, onValueChange, isDisabled, name, ...props }: SwitchProps) { const [internal, setInternal] = useState(defaultSelected); const checked = isSelected ?? internal; return <><RadixSwitch.Root checked={checked} disabled={isDisabled} onCheckedChange={(value) => { if (isSelected === undefined) setInternal(value); onValueChange?.(value); }} className="relative h-6 w-10 shrink-0 rounded-full bg-[var(--control-track)] outline-none transition-colors data-[state=checked]:bg-[#0066cc] focus-visible:ring-4 focus-visible:ring-link/25 disabled:opacity-45 dark:data-[state=checked]:bg-[#64a8ff]" {...props}><RadixSwitch.Thumb className="block h-5 w-5 translate-x-0.5 rounded-full bg-white shadow-sm transition-transform data-[state=checked]:translate-x-[18px]" /></RadixSwitch.Root>{name && <input type="hidden" name={name} value={checked ? 'on' : ''} />}</>; }

export function Progress({ value = 0, className, classNames, color, size: _size, ...props }: { value?: number; className?: string; classNames?: Record<string, string>; color?: string; size?: string; 'aria-label'?: string }) { return <div className={cn('h-2 w-full overflow-hidden rounded-full bg-[var(--control-track)]', classNames?.track, className)} role="progressbar" aria-valuemin={0} aria-valuemax={100} aria-valuenow={value} {...props}><div className={cn('h-full rounded-full bg-[#0066cc] transition-[width] duration-500 dark:bg-[#64a8ff]', color === 'danger' && 'bg-red-700', color === 'success' && 'bg-emerald-700', classNames?.indicator)} style={{ width: `${Math.min(100, Math.max(0, value))}%` }} /></div>; }
export const Divider = ({ orientation, className }: { orientation?: 'horizontal' | 'vertical'; className?: string }) => <div className={cn(orientation === 'vertical' ? 'h-full w-px' : 'h-px w-full', 'bg-input', className)} />;
export function Chip({ children, className, color, ...props }: { children: ReactNode; className?: string; color?: string; size?: string; variant?: string }) { return <span className={cn('inline-flex h-6 items-center rounded-full bg-secondary px-2.5 text-[11px] font-medium text-secondary-foreground', color === 'success' && 'bg-emerald-100 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-200', color === 'warning' && 'bg-amber-100 text-amber-900 dark:bg-amber-950 dark:text-amber-200', color === 'danger' && 'bg-red-100 text-red-800 dark:bg-red-950 dark:text-red-200', className)} {...props}>{children}</span>; }
export function Avatar({ name = '', className }: { name?: string; size?: string; className?: string }) { return <span className={cn('grid h-8 w-8 place-items-center rounded-full bg-secondary text-xs font-semibold text-foreground ring-1 ring-input', className)}>{name.trim().slice(0, 2).toUpperCase()}</span>; }

export const Dropdown = RadixDropdown.Root;
export const DropdownTrigger = ({ children }: { children: ReactElement }) => <RadixDropdown.Trigger asChild>{children}</RadixDropdown.Trigger>;
export function DropdownMenu({ children, ...props }: { children: ReactNode; 'aria-label'?: string }) { return <RadixDropdown.Portal><RadixDropdown.Content sideOffset={7} align="end" className="z-[100] min-w-44 rounded-xl border border-input bg-popover p-1.5 text-popover-foreground shadow-[0_16px_48px_rgba(0,0,0,.16)] backdrop-blur-2xl outline-none" {...props}>{children}</RadixDropdown.Content></RadixDropdown.Portal>; }
export function DropdownItem({ children, onPress, href, color, startContent, isReadOnly }: { children: ReactNode; onPress?: () => void; href?: string; color?: string; startContent?: ReactNode; isReadOnly?: boolean }) { return <RadixDropdown.Item disabled={isReadOnly} onSelect={() => { onPress?.(); if (href) window.location.href = href; }} className={cn('flex cursor-default select-none items-center gap-2 rounded-lg px-2.5 py-2 text-sm text-popover-foreground outline-none transition data-[highlighted]:bg-secondary data-[disabled]:opacity-50', color === 'danger' && 'text-red-700 data-[highlighted]:bg-red-50 dark:text-red-300 dark:data-[highlighted]:bg-red-950')}>{startContent}{children}</RadixDropdown.Item>; }

export function Tooltip({ children, content }: { children: ReactElement; content: ReactNode }) { return <RadixTooltip.Provider delayDuration={350}><RadixTooltip.Root><RadixTooltip.Trigger asChild>{children}</RadixTooltip.Trigger><RadixTooltip.Portal><RadixTooltip.Content sideOffset={6} className="z-[110] rounded-lg bg-zinc-950 px-2.5 py-1.5 text-xs text-white shadow-lg">{content}<RadixTooltip.Arrow className="fill-zinc-950" /></RadixTooltip.Content></RadixTooltip.Portal></RadixTooltip.Root></RadixTooltip.Provider>; }

export const Modal = ({ isOpen, onClose, children }: { isOpen: boolean; onClose: () => void; children: ReactNode; placement?: string; scrollBehavior?: string; classNames?: Record<string, string> }) => <Dialog.Root open={isOpen} onOpenChange={(open) => !open && onClose()}>{children}</Dialog.Root>;
export function ModalContent({ children }: { children: ReactNode }) { return <Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-[120] bg-black/35 backdrop-blur-[3px] data-[state=open]:animate-in data-[state=closed]:animate-out"/><Dialog.Content className="fixed left-1/2 top-1/2 z-[121] flex max-h-[88dvh] w-[calc(100%-2rem)] max-w-lg -translate-x-1/2 -translate-y-1/2 flex-col overflow-hidden rounded-[24px] border border-input bg-popover text-popover-foreground shadow-[0_28px_80px_rgba(0,0,0,.28)] backdrop-blur-2xl outline-none [&>form]:contents"><Dialog.Close type="button" className="absolute right-4 top-4 z-10 grid h-8 w-8 place-items-center rounded-full bg-secondary text-foreground transition hover:brightness-95 focus-visible:ring-2 focus-visible:ring-link" aria-label="閉じる"><X size={15}/></Dialog.Close>{children}</Dialog.Content></Dialog.Portal>; }
export const ModalHeader = ({ children }: { children: ReactNode }) => <Dialog.Title className="shrink-0 border-b border-border px-6 py-5 pr-14 text-lg font-semibold tracking-[-.02em] text-popover-foreground">{children}</Dialog.Title>;
export const ModalBody = ({ className, ...props }: HTMLAttributes<HTMLDivElement>) => <div className={cn('flex min-h-0 flex-1 flex-col overflow-y-auto overscroll-contain px-6 py-5', className)} {...props} />;
export const ModalFooter = ({ className, ...props }: HTMLAttributes<HTMLDivElement>) => <div className={cn('sticky bottom-0 z-[2] flex shrink-0 justify-end gap-2 border-t border-border bg-popover px-6 py-4', className)} {...props} />;

type TabsContextValue = { selected?: string; setSelected: (value: string) => void };
const TabsContext = createContext<TabsContextValue>({ setSelected: () => {} });
export function Tabs({ children, selectedKey, onSelectionChange, className }: { children: ReactNode; selectedKey?: string; onSelectionChange?: (key: string) => void; color?: string; variant?: string; className?: string }) { const tabs = Children.map(children, (child) => isValidElement(child) ? cloneElement(child as ReactElement<{ tabKey?: string }>, { tabKey: String(child.key) }) : child); return <TabsContext.Provider value={{ selected: selectedKey, setSelected: (key) => onSelectionChange?.(key) }}><div className={cn('inline-flex rounded-xl bg-secondary p-1', className)}>{tabs}</div></TabsContext.Provider>; }
export function Tab({ title, tabKey = '' }: { title: ReactNode; tabKey?: string }) { const context = useContext(TabsContext); return <button type="button" onClick={() => context.setSelected(tabKey)} className={cn('rounded-lg px-3 py-1.5 text-xs font-medium text-muted-foreground transition focus-visible:ring-2 focus-visible:ring-link', context.selected === tabKey && 'bg-card text-foreground shadow-sm')}>{title}</button>; }

export const Link = ({ className, ...props }: AnchorHTMLAttributes<HTMLAnchorElement>) => <a className={cn('text-link underline-offset-4 hover:underline focus-visible:rounded focus-visible:ring-2 focus-visible:ring-link', className)} {...props} />;
